name: Lint
on:
  push:
    branches: [main]
    paths:
      - '**.sh'
  pull_request:
    branches: [main]
    paths:
      - '**.sh'

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

      actions: read
      contents: read

    steps:
      - name: Repoitory Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: ShellCheck
        name: ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
